### ISSUE TITLE
Unable to download

### ISSUE THREAD

**Issue by sonofthehunt** [wmw9/cyberdrop-dl#2]
Downloading starts off real smooth, and about half of the images in the album is downloaded. However the speed of the download significantly decreases, almost to nil. Additionally, this error appears periodically:
![image](https://user-images.githubusercontent.com/83547482/126158187-c60d7fef-7425-4fb9-ae59-d0c32d3037b1.png)

If the problem is on my side, help would be very much appreciated. In any case, I really like this downloader as opposed to the other ones available. TYIA!

**Comment by sonofthehunt** [comment]
I initially thought that it may be caused by the large number of albums I was downloading (~~70~~ 69) so I cut it down to groups of 10 albums which is shown in the image I have attached above

**Comment by evan-sm** [comment]
Okay, will look at it.

Could you please share list of albums?

**Comment by sonofthehunt** [comment]
Full list: https://pastebin.com/ignRqQSG (69 lines)
Particular group of 10 I was currently downloading: https://pastebin.com/ikdGy1u3

**Comment by evan-sm** [comment]
Looks like cyberdrop.me from time to time is having high-load and sometimes fails to send data to user. But, client side can also implement retry strategy and additional checks for certain files being missed or not being downloaded properly.
It is a good idea to download albums by small steps. You could also hardcode here https://github.com/wmw9/cyberdrop-dl/blob/main/src/lib.rs#L20 to download less albums per step simultaneously if you're not in hurry, this way it'll be much stable, but slowly.

Will try to make retry strategy when I have free time 🎆

**Comment by sonofthehunt** [comment]
Alrighty! Thanks! Closing this since it seems to have solved my problem :>

**Comment by sonofthehunt** [comment]
I don't know anything about coding in rust so please let me know what I'm doing wrong here. I downloaded the repository (using git) and edited only that specific part of lib.rs. However when trying to build/compile it, it gives this error:
![image](https://user-images.githubusercontent.com/83547482/126496036-52378da4-7b8f-4278-a7ea-fca76e9510f7.png)
 help?

tyia!

**Comment by sonofthehunt** [comment]
I don't know much about rust code so I might be doing something wrong here. I edited that part of the lib.rs and tried compiling it but gives me this error:
![image](https://user-images.githubusercontent.com/83547482/126496324-60fb6d62-c4e5-43e0-b36d-67e1b9ed3cc3.png)

help is greatly appreciated. TYIA

**Comment by evan-sm** [comment]
> I don't know much about rust code so I might be doing something wrong here. I edited that part of the lib.rs and tried compiling it but gives me this error:
> ![image](https://user-images.githubusercontent.com/83547482/126496324-60fb6d62-c4e5-43e0-b36d-67e1b9ed3cc3.png)
> 
> help is greatly appreciated. TYIA

It is just a warning. Binary was succesfully created inside ./target/debug/cyberdrop-dl folder. Or just try another command "cargo run" instead "cargo build".

Would be better if you used [WSL2](https://docs.microsoft.com/en-us/windows/wsl/install-win10) instead PowerShell.

**Comment by sonofthehunt** [comment]
> Would be better if you used WSL2 instead PowerShell.

noted on that.

I'll just add it to PATH for now. Thanks!
