### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by KenoFaustino** [wmw9/cyberdrop-dl#3]
![image](https://user-images.githubusercontent.com/74803630/132998014-7a57bf29-bddf-4f27-9d80-26310434c0be.png)

I installed Rust according to the guide, tried using cargo and it came up like this. Is there any solution to fix this?

**Comment by evan-sm** [comment]
See, link.exe not found. If using Windows cmd you need "MS VS Redistributable" installed to compile. Details is [here](https://www.jaacostan.com/2019/12/rust-error-linker-linkexe-not-found.html?m=1)

But, I would recommend you to ditch out cmd and use bash WSL2. Google "how to install WSL2".

**Comment by Liz-chan** [comment]
I compiled it and uploaded it here, I think it should work by itself: https://pixeldrain.com/u/pAY6SBUx

**Comment by evan-sm** [comment]
We now have prebuilt executable downloadable binaries, thanks to @cyberdrop-me 

https://github.com/wmw9/cyberdrop-dl/releases
